I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 92, in script
    define mc = Character("[mcname]", color = "#ffffff", ctc="ctc_blink", image="gwyn", window_background="gui/textbox2.png", what_outlines = ((0, "#6529233d", -2, 2), (2, "#65292318", -3, 3), (1, "#6529230e", -4, 4),(0, "#6529233d", 2, -2), (2, "#65292318", 3, -3), (1, "#6529230e", 4, -4)(0, "#6529233d", -2, -2), (2, "#65292318", -3, -3), (1, "#6529230e", -4, -4),(0, "#6529233d", 2, 2), (2, "#65292318", 3, 3), (1, "#6529230e", 4, 4)))
  File "game/script.rpy", line 92, in <module>
    define mc = Character("[mcname]", color = "#ffffff", ctc="ctc_blink", image="gwyn", window_background="gui/textbox2.png", what_outlines = ((0, "#6529233d", -2, 2), (2, "#65292318", -3, 3), (1, "#6529230e", -4, 4),(0, "#6529233d", 2, -2), (2, "#65292318", 3, -3), (1, "#6529230e", 4, -4)(0, "#6529233d", -2, -2), (2, "#65292318", -3, -3), (1, "#6529230e", -4, -4),(0, "#6529233d", 2, 2), (2, "#65292318", 3, 3), (1, "#6529230e", 4, 4)))
TypeError: 'tuple' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 92, in script
    define mc = Character("[mcname]", color = "#ffffff", ctc="ctc_blink", image="gwyn", window_background="gui/textbox2.png", what_outlines = ((0, "#6529233d", -2, 2), (2, "#65292318", -3, 3), (1, "#6529230e", -4, 4),(0, "#6529233d", 2, -2), (2, "#65292318", 3, -3), (1, "#6529230e", 4, -4)(0, "#6529233d", -2, -2), (2, "#65292318", -3, -3), (1, "#6529230e", -4, -4),(0, "#6529233d", 2, 2), (2, "#65292318", 3, 3), (1, "#6529230e", 4, 4)))
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.1-sdk\renpy\ast.py", line 2508, in execute
    self.set()
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.1-sdk\renpy\ast.py", line 2522, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.1-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 92, in <module>
    define mc = Character("[mcname]", color = "#ffffff", ctc="ctc_blink", image="gwyn", window_background="gui/textbox2.png", what_outlines = ((0, "#6529233d", -2, 2), (2, "#65292318", -3, 3), (1, "#6529230e", -4, 4),(0, "#6529233d", 2, -2), (2, "#65292318", 3, -3), (1, "#6529230e", 4, -4)(0, "#6529233d", -2, -2), (2, "#65292318", -3, -3), (1, "#6529230e", -4, -4),(0, "#6529233d", 2, 2), (2, "#65292318", 3, 3), (1, "#6529230e", 4, 4)))
TypeError: 'tuple' object is not callable

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Gwetome Academy 1.0
Thu Feb  1 23:43:32 2024
